name: Deploy Challenges to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to github pages
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                rm -rf gh-pages-output
                mkdir gh-pages-output
                find newbie/* -type d -exec cp -R {} gh-pages-output/ \;
                cd gh-pages-output

                git init
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "Deploy challenges to GitHub Pages"
                git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" master:gh-pages